//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje22_entity_
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbladmin
    {
        public byte id { get; set; }
        public string kullanıcı { get; set; }
        public string sifre { get; set; }
    }
}
